const mongoose = require("mongoose");

const roleSchema = new mongoose.Schema(
  {
    roleName: {
      type: String,
      required: [true, "Please provide a role name"],
      unique: true,
      trim: true,
      maxlength: [50, "Role name cannot be more than 50 characters"],
    },
    permissions: [
      {
        type: String,
        enum: [
          "dashboard.view",
          "sales.create",
          "sales.view",
          "sales.update",
          "sales.delete",
          "purchase.create",
          "purchase.view",
          "purchase.update",
          "purchase.delete",
          "inventory.create",
          "inventory.view",
          "inventory.update",
          "inventory.delete",
          "recipe.create",
          "recipe.view",
          "recipe.update",
          "recipe.delete",
          "party.create",
          "party.view",
          "party.update",
          "party.delete",
          "expense.create",
          "expense.view",
          "expense.update",
          "expense.delete",
          "offers.create",
          "offers.view",
          "offers.update",
          "offers.delete",
          "items.create",
          "items.view",
          "items.update",
          "items.delete",
          "reports.view",
          "users.create",
          "users.view",
          "users.update",
          "users.delete",
          "kot.create",
          "kot.view",
          "kot.update",
          "roles.create",
          "roles.view",
          "roles.update",
          "roles.delete",
          "labour.create",
          "labour.view",
          "labour.update",
          "labour.delete",
          "labourAttendance.create",
          "labourAttendance.view",
          "labourAttendance.update",
          "labourAttendance.delete",
          "shop.create",
          "shop.view",
          "shop.update",
          "shop.delete",
          "itemCategory.create",
          "itemCategory.view",
          "itemCategory.update",
          "itemCategory.delete",
          "itemSubCategory.create",
          "itemSubCategory.view",
          "itemSubCategory.update",
          "itemSubCategory.delete",
          "brand.create",
          "brand.view",
          "brand.update",
          "brand.delete",
          // ADD THESE REFERRER PERMISSIONS
          "referrer.create",
          "referrer.view",
          "referrer.update",
          "referrer.delete",
          "coupon.view",
          "coupon.create",
          "coupon.update",
          "coupon.delete",
          "token.delete",
          "token.view",
          "token.update",
          "token.create",
        ],
      },
    ],
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// This line is the key fix. It checks if the model already exists before compiling.
module.exports = mongoose.models.Role || mongoose.model("Role", roleSchema);
